#!/usr/bin/env python3
"""Turn venues.csv into an idempotent seed of unclaimed karaoke VENUE listings.

Mirrors the salon-template directory seed: owner-less rows, claimed=false,
source='osm', not yet published/bookable — they appear in the directory so
customers can find them and owners can later claim their page.
"""
import csv, re, os

HERE = os.path.dirname(__file__)

def slugify(s):
    s = re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')
    return s[:48] or 'venue'

def sql(v):
    if v is None or v == '':
        return 'null'
    return "'" + str(v).replace("'", "''") + "'"

def classify(name, amenity):
    """Two venue categories (DJs are added by users, not seeded from OSM):
       'karaoke_bar'      — dedicated karaoke / KTV spot
       'bar_with_karaoke' — a bar that also has karaoke
    plus a karaoke_type heuristic: dedicated KTV/'box' spots are in-room,
    bars that host karaoke are open-mic."""
    n = name.lower()
    dedicated = amenity in ('karaoke', 'karaoke_box') or 'ktv' in n or 'karaoke' in n
    if dedicated:
        ktype = 'in_room' if (amenity == 'karaoke_box' or 'ktv' in n or 'room' in n) else 'both'
        return 'karaoke_bar', ktype
    return 'bar_with_karaoke', 'open'

rows, seen = [], set()
with open(os.path.join(HERE, 'venues.csv'), encoding='utf-8') as f:
    for r in csv.DictReader(f):
        base = slugify(r['name'])
        slug = f"{base}-{r['osm_id'][-5:]}"
        if slug in seen:
            slug = f"{base}-{r['osm_id']}"
        seen.add(slug)
        city = r['city']
        if city and r['state']:
            city = f"{city}, {r['state']}"
        elif r['state']:
            city = r['state']
        btype, ktype = classify(r['name'], r['amenity'])
        rows.append({
            'name': r['name'], 'slug': slug,
            'business_type': btype, 'karaoke_type': ktype,
            'phone': r['phone'], 'address': r['address'], 'city': city,
            'website': r['website'] or None,
            'lat': r['lat'], 'lon': r['lon'],
        })

out = os.path.join(HERE, 'seed_venues.sql')
with open(out, 'w', encoding='utf-8') as f:
    f.write("-- Karaoke Bar Map — seed of unclaimed US karaoke venues (OpenStreetMap).\n")
    f.write("-- Generated by make_seed.py. Safe to re-run (on conflict do nothing by slug).\n\n")
    f.write("insert into public.salons\n")
    f.write("  (name, slug, business_type, karaoke_type, phone, address, city, website, "
            "lat, lon, claimed, source, is_published, currency, timezone)\nvalues\n")
    vals = []
    for r in rows:
        vals.append(
            "  (" + ", ".join([
                sql(r['name']), sql(r['slug']), sql(r['business_type']), sql(r['karaoke_type']),
                sql(r['phone']), sql(r['address']), sql(r['city']), sql(r['website']),
                r['lat'], r['lon'], "false", "'osm'", "false", "'USD'", "'America/New_York'",
            ]) + ")"
        )
    f.write(",\n".join(vals))
    f.write("\non conflict (slug) do nothing;\n")

print(f"seed_venues.sql: {len(rows)} venue listings")
